### ISSUE TITLE
No Issue, just thanks

### ISSUE THREAD

**Issue by zapbra** [kmvan/react-mde#1]
No issues, I just wanted to thank you for fixing this project. I saw it was broken and not working in react 18, and you commented that you updated it and I just implemented it with your codesandbox and it works great, no issues whatsoever. I got an error at first, but didn't change some of the props to what you updated them.

Great work and it pushed to vercel with no errors :)

**Comment by kmvan** [comment]
> No issues, I just wanted to thank you for fixing this project. I saw it was broken and not working in react 18, and you commented that you updated it and I just implemented it with your codesandbox and it works great, no issues whatsoever. I got an error at first, but didn't change some of the props to what you updated them.
> 
> Great work and it pushed to vercel with no errors :)

Sorry to late reply. I updated.
